version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 2170:27017
    networks:
      - app
    volumes:
      - mongo-data:/data/db
  apiserver:
    container_name: apiserver
    restart: always
    env_file:
      - ./api/.env
    environment:
      - PORT=3000
      - DB_PROTOCOL=mongodb
      - DB_USERNAME=admin
      - DB_PASSWORD=password
      - DB_URI=mongo:27017
      - DB_NAME=gamedb
      - API_URL=http://localhost:8080
      - CLIENT_URL=http://localhost:3000
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    links:
      - mongo
    networks:
      - app

networks: # изолируем от другик контейнеров на сервере
  app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
