version: '3.4'

services:
  gamebackend:
    container_name: gamebackend
    restart: always
    build:
      context: ./gameBackend
      dockerfile: ./Dockerfile
    ports:
      - 80:3000
    links:
      - mongo
  auth:
    container_name: authserver
    restart: always
    build:
      context: ./auth
      dockerfile: ./Dockerfile
    ports:
      - 300:3300
  mongo:
    container_name: mongo
    build:
      context: ./DB
      dockerfile: ./Dockerfile
    ports:
      - 2170:21017
