version: '3.7'

services:
  apiserver:
    container_name: apiserver
    restart: always
    env_file:
      - ./api/.env
    build: ./api
    ports:
      - 8080:3000
    links:
      - mongo
    networks:
      - app

  mongo:
    image: mongo:latest
    container_name: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: pskrhbvkshl2i9r870k
    ports:
      - 2170:27017
    networks:
      - app
    volumes:
      - mongo-data:/data/db

networks: # изолируем от другик контейнеров на сервере
  app:
    driver: bridge
volumes:
  mongo-data:
    driver: local

